# Generated by Django 4.0.6 on 2022-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_student_class_section_alter_student_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('DS', 'Select the Stream if your class greater than 10'), ('S', 'SCIENCE'), ('C', 'COMMERCE'), ('A', 'ARTS')], max_length=5),
        ),
    ]
