# Generated by Django 4.0.6 on 2022-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_student_roll_no_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('DS', 'Select the Stream if your class greater than 10'), ('SCIENCE', 'SCIENCE'), ('COMMERCE', 'COMMERCE'), ('ARTS', 'ARTS')], max_length=10),
        ),
    ]
